### ISSUE TITLE
org.evosuite.testsuite.TestSuiteChromosome cannot be cast to org.evosuite.testcase.TestChromosome

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/botsing#100]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: Evosuite v1.0.7 snapshot
- **Execution Environment**: CentOS7
- **Reporter**: Jesús Gorroñogoitia<jesus.gorronogoitia@atos.net>

#### Description

Evosuite seems not to work when executed with -prefix flag. It works well with -class flag instead.
When run with -prefix flag, I get this error:

```
[MASTER] 14:56:52.949 [logback-2] ERROR ClientNodeImpl - Error when generating tests for: eu.supersede.integration.api.security.types.Role with seed 1570546603549. Configuration id : null
java.lang.ClassCastException: org.evosuite.testsuite.TestSuiteChromosome cannot be cast to org.evosuite.testcase.TestChromosome
	at org.evosuite.ga.metaheuristics.mosa.structural.MultiCriteriatManager.calculateFitness(MultiCriteriatManager.java:363) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.mosa.DynaMOSA.calculateFitness(DynaMOSA.java:237) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.GeneticAlgorithm.calculateFitness(GeneticAlgorithm.java:601) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.mosa.AbstractMOSA.initializePopulation(AbstractMOSA.java:335) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.ga.metaheuristics.mosa.DynaMOSA.generateSolution(DynaMOSA.java:148) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.strategy.WholeTestSuiteStrategy.generateTests(WholeTestSuiteStrategy.java:113) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTests(TestSuiteGenerator.java:676) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:244) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:160) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]
[MASTER] 14:56:53.061 [main] ERROR SearchStatistics - No statistics has been saved because EvoSuite failed to generate any test case
[MASTER] 14:56:53.163 [main] ERROR TestGeneration - failed to write statistics data
```

#### Steps to reproduce
Experiements are executed with this script:
root@supersede:/home# cat run_evosuite.sh 
```
java -d64 -Xmx4000m -jar supersede-if-botsing/evosuite-master-1.0.7-SNAPSHOT.jar \
	-prefix "$1" \
	-projectCP "$(cat results/classpath.txt)" \
	-generateMOSuite \
	-Dalgorithm=DynaMOSA \
	-Dsearch_budget=60 \
	-Dseed_clone="0.5" \
	-Donline_model_seeding=TRUE \
	-Dmodel_path="results/models" \
	-Dtest_dir="results/evosuite-tests" \
	-Dreport_dir="results/evosuite-report" \
	-Dno_runtime_dependency=true \
	-Dsandbox=False
```
which is invoked with:`./run_evosuite.sh eu.supersede.integration.api.security.types`

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by jesus-gorronogoitia** [comment]
Can you reproduce it, using -prefix in some example of yours, or is it something specific to our UC. In the former case, I guess it would be easy for you to debug it. In the latter, we can meet together tomorrow trying to debug it.

**Comment by pderakhshanfar** [comment]
I did an investigation on this one. Apparently, EvoSuite puts a limitation on the number of iterations that we can have in the loops of software under test. Fortunately, you can modify this limitation by `-Dmax_loop_iterations=<new_limitation>`.

**Comment by pderakhshanfar** [comment]
I think DynaMosa, which is the best algorithm in EvoSuite (according to literature), works only with `-class` not `-prefix`. Also, testing only one class is more tested in EvoSuite because this is the common way of using it.

**Comment by pderakhshanfar** [comment]
One point, the issues which are related to running EvoSuite+model seeding should be in the [repository of EvoSuite](https://github.com/STAMP-project/evosuite/issues). I will transfer this issue there.
