### ISSUE TITLE
Evosuite with model seeding crashing

### ISSUE THREAD

**Issue by vmassol** [STAMP-project/botsing#105]
When executed on xwiki-commons-properties, I got:

```
...
* Property NO_RUNTIME_DEPENDENCY is set to true - skipping JUnit compile check
* WARNING: Not including the runtime dependencies is likely to lead to flaky tests!
* Writing tests to file
* Writing JUnit test case 'CollectionConverter_ESTest' to target/botsing/evosuite-tests
* Done!

* Computation finished
* Current class: org.xwiki.properties.internal.converter.TypeConverter
* Going to generate test cases for class: org.xwiki.properties.internal.converter.TypeConverter
* Starting Client-0
* Connecting to master process on port 16670
[MASTER] 15:02:22.300 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class org.xwiki.properties.internal.converter.TypeConverter using seed 1570798466322. Configuration id : null
java.lang.NullPointerException: null
	at org.evosuite.utils.ExternalProcessGroupHandler.waitForResult(ExternalProcessGroupHandler.java:694) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.generateTests(TestGeneration.java:515) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.generateTestsTarget(TestGeneration.java:638) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.executeTestGeneration(TestGeneration.java:85) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:308) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.main(EvoSuite.java:341) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
* Analyzing classpath: 
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-properties (master) $ 
```

**Comment by vmassol** [comment]
Same crash for xwiki-commons-velocity:

```
[MASTER] 16:01:16.649 [main] ERROR EvoSuite - Fatal crash on main EvoSuite process. Class org.xwiki.velocity.internal.util.VelocityParserContext using seed 1570801865603. Configuration id : null
java.lang.NullPointerException: null
	at org.evosuite.utils.ExternalProcessGroupHandler.waitForResult(ExternalProcessGroupHandler.java:694) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.generateTests(TestGeneration.java:515) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.generateTestsTarget(TestGeneration.java:638) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.executionmode.TestGeneration.executeTestGeneration(TestGeneration.java:85) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.parseCommandLine(EvoSuite.java:308) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
	at org.evosuite.EvoSuite.main(EvoSuite.java:341) ~[evosuite-master-1.0.7-SNAPSHOT.jar:1.0.7-SNAPSHOT]
* Analyzing classpath: 
vmassol ~/dev/xwiki/xwiki-commons/xwiki-commons-core/xwiki-commons-velocity (master *+) $ 
```
