### ISSUE TITLE
Not finding Java compiler

### ISSUE THREAD

**Issue by ltboye** [STAMP-project/botsing#11]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: block
- **Tool/Service/Component**: Botsing
- **Execution Environment**: Windows 10, Eclipse Photon
- **Reporter**: Lars Thomas Boye

#### Description
I tried running Botsing on the XWIKI-13031 case from EvoCrash-demo. I got it running in Eclipse, based on a SimpleCrashReproductionTest from @pderakhshanfar . It runs for about a minute, before stopping with the exception below.
JAVA_HOME points to jdk1.8.0_172. Eclipse is set up to use the same.

I suspect this is a Windows-thing. Note that the old EvoCrash-demo runs on my system, so I don't see why this can't be fixed. Also note that I encountered a similar problem with the current DSpot version, with it complaining about not finding the JDK.

java.lang.RuntimeException: No Java compiler is available. Make sure to run EvoSuite with the JDK and not the JRE.You can try to setup the JAVA_HOME system variable to point to it, as well as to make sure that the PATH variable points to the JDK before any JRE.
	at eu.stamp.botsing.reproduction.CrashReproduction.compileAndCheckTests(CrashReproduction.java:270)
	at eu.stamp.botsing.reproduction.CrashReproduction.postProcessTests(CrashReproduction.java:161)
	at eu.stamp.botsing.reproduction.CrashReproduction.generateCrashReproductionTests(CrashReproduction.java:126)
	at eu.stamp.botsing.reproduction.CrashReproduction.execute(CrashReproduction.java:78)
	at eu.stamp.botsing.Botsing.parseCommandLine(Botsing.java:96)
	at eu.stamp.botsing.SimpleCrashReproductionTest.runtest(SimpleCrashReproductionTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

**Comment by pderakhshanfar** [comment]
I think the problem can be one of these two reasons:
1- Botsing does not support java version > 8 yet.
2- You may need to use -Dtools_jar_location=<path> property to point the tools.jar file in your JDK directory

**Comment by spookyvale** [comment]
I'll try the same example (SimpleCrashReproductionTest) under windows and let you know.
@ltboye, have you tried to run it outside Eclipse environment? I sometimes get strange results when running tools from within eclipse.

**Comment by ltboye** [comment]
@pderakhshanfar I use Java 8. Which versions are supported?
I will try the tools_jar_location tomorrow (am out of office the rest of today).

@spookyvale I have so far only tried Botsing in Eclipse. I can try outside tomorrow. I have a similar error with DSpot, both from command line and in Eclipse.

**Comment by pderakhshanfar** [comment]
@ltboye Any version of JDK 8 should be ok.

**Comment by ltboye** [comment]
@spookyvale I made a simple test class to run Botsing with the XWIKI-13031 case from EvoCrash-demo, based on an example from @pderakhshanfar . I only have that locally at my office machine and am out of office now, but I can send you my file tomorrow morning.

**Comment by spookyvale** [comment]
In the meantime I will try with some other example. I'll let you know.
About Dspot, I know the latest versions should have a better support for Win OS

**Comment by ltboye** [comment]
@pderakhshanfar I added -Dtools_jar_location to the properties given to botsing.parseCommandLine, pointing to the tools.jar file in the JDK. I know this property is used, because if I set the wrong path it stops with an error on startup. With the right path it runs and gives the same error as before (No Java compiler is available).

**Comment by spookyvale** [comment]
Hello.
I added the test to botsing-reproduction and tried it with `mvn clean test` from both inside and outside Eclipse.
It runs without errors. 
One thing that comes to my mind (but only from within eclipse) is that my eclipse runs itself from a JDK. I had to do that for another project in the past because tools.jar dependency usually has a system scope. (see [this](https://stackoverflow.com/questions/5273792/missing-tools-jar-in-local-repository-breaks-m2eclipse/16140087)).
I did not even have to set the` -Dtools_jar_location`.

From the system console I did not get errors either. Only make sure the Java distribution maven uses is a JDK.

**Comment by ltboye** [comment]
Running with Maven (mvn test) from command line, it works!

I will try a bit more to get it running in Eclipse, but now at least I have a way to run it.

**Comment by ltboye** [comment]
Now I got it working in Eclipse as well.

The problem was that, even though Eclipse itself was using the jdk for compilation, the project build path was pointing to the jar files of the jre. Changing the project build path to use the jars of the jdk, the problem was fixed.
