### ISSUE TITLE
What kind of stack traces and frame level are passed to Botsing

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/botsing#16]
#### Characteristics
- **Issue Type**: question
- **Reproducibility**: N/A
- **Severity**: major
- **Tool/Service/Component**: Botsing
- **Execution Environment**:  All platform, OS (Windows, Linux)
- **Reporter**: Jesús Gorroñogoitia <jesus.gorronogoitia@atos.net>

#### Description
Supposed we want to use Botsing to generate test cases that reproduce this stack trace:
`org.apache.axis2.AxisFault: Username 'pilar' already exists in the system. Please pick another username.
        at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
        at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
        at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.addUser(RemoteUserStoreManagerServiceStub.java:2276)
        at eu.supersede.integration.api.security.IFUserStoreManager.addUser(IFUserStoreManager.java:139)
        at eu.supersede.integration.api.security.IFAuthenticationManager.addUser(IFAuthenticationManager.java:159)
        at eu.supersede.fe.rest.UserRest.createUser(UserRest.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)`

where real Atos code traces are:
`at eu.supersede.integration.api.security.IFUserStoreManager.addUser(IFUserStoreManager.java:139)
        at eu.supersede.integration.api.security.IFAuthenticationManager.addUser(IFAuthenticationManager.java:159)
        at eu.supersede.fe.rest.UserRest.createUser(UserRest.java:72)`

**Question 1**
What should be the stack trace I should pass to Botsing? The complete one? a version that gets rid of every below the first Atos code frame ` at eu.supersede.fe.rest.UserRest.createUser(UserRest.java:72)`

I mean, should I pass this stack trace?:
`org.apache.axis2.AxisFault: Username 'pilar' already exists in the system. Please pick another username.
        at org.apache.axis2.util.Utils.getInboundFaultFromMessageContext(Utils.java:531)
        at org.apache.axis2.description.RobustOutOnlyAxisOperation$RobustOutOnlyOperationClient.handleResponse(RobustOutOnlyAxisOperation.java:91)
        at org.apache.axis2.description.OutInAxisOperationClient.send(OutInAxisOperation.java:421)
        at org.apache.axis2.description.OutInAxisOperationClient.executeImpl(OutInAxisOperation.java:229)
        at org.apache.axis2.client.OperationClient.execute(OperationClient.java:165)
        at org.wso2.carbon.um.ws.api.stub.RemoteUserStoreManagerServiceStub.addUser(RemoteUserStoreManagerServiceStub.java:2276)
        at eu.supersede.integration.api.security.IFUserStoreManager.addUser(IFUserStoreManager.java:139)
        at eu.supersede.integration.api.security.IFAuthenticationManager.addUser(IFAuthenticationManager.java:159)
        at eu.supersede.fe.rest.UserRest.createUser(UserRest.java:72)`

I think so, because deeper frames in the stack trace are JVM executions of the Tomcat server, and I assume we can ignore Application Server execution. 

**Question 2**
Then, if so, and I am interesting in reproducing my code only, I assume that the correct frame level would be 3, so frame `at eu.supersede.integration.api.security.IFUserStoreManager.addUser(IFUserStoreManager.java:139)` is the last one reproduced by the test. Is this correct?

What about if I don't want Botsing start with frame ` at eu.supersede.fe.rest.UserRest.createUser(UserRest.java:72)` but  with the next one, can I just drop it from the stack trace?

**Question 3**
What are the libraries I should provide to Botsing? I assume only those required to execute the code in the stack trace from the first frame onwards, in particular all libraries containing the following packages and all its dependencies required to execute them:
```
org.apache.axis2.description
org.apache.axis2.client
org.wso2.carbon.um.ws.api.stub
eu.supersede.integration.api.security
eu.supersede.fe.rest
```
They are bundled in the WAR file, so I can extract them and place them in a folder.

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by pderakhshanfar** [comment]
@jesus-gorronogoitia For now, the stack trace should be a non-chained stack trace; It should start with the type of the exception in the first line and the frames in the next lines. 
### Question 1
You should not remove frames which point to the dependencies of the project or Java libraries. They should be there in the stack trace. However, you cannot pass these frames as the target frame.

### Question 2
Any frames which point to the software under test can be set as the target frame.

### Question 3
Yes, It is true. Also, If Botsing cannot find a class in the given classpath, it will inform you in the output.
