### ISSUE TITLE
Release doesn't contains dependencies making them unexecutable without errors

### ISSUE THREAD

**Issue by MaelAudren** [STAMP-project/botsing#27]
#### Characteristics
- **Issue Type**: [bug]
- **Reproducibility**: [always]
- **Severity**: [major]
- **Tool/Service/Component**: [All release]
- **Reporter**: [Mael Audren, mael.audren@activeeon.com]

#### Description
When executing Botsing on my log and libraries I got the exception
``` java.lang.NoClassDefFoundError: org/junit/Test```. I manage to remove the error by adding the jar junit-4.12.jar. Then I got exceptions with the missing classes hamcrest, mockito that I manage to fix by adding those jars with  the botsing version. Then I got another missing dependencies. Adding the jars manually is not the good solution. 

How can I generate or get botsing release with the dependencies ?

#### Steps to reproduce

Get the scheduling project libraries
```
git clone https//github.com/ow2-proactive/scheduling
./gradlew clean build -x test
```

Create the SpaceNotFound.log file with the following stack trace
```
org.objectweb.proactive.extensions.dataspaces.exceptions.SpaceNotFoundException: Requested data space is not registered in spaces directory.
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.ensureVirtualSpaceIsMounted(VFSSpacesMountManagerImpl.java:247)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:159)
    at org.objectweb.proactive.extensions.dataspaces.vfs.VFSSpacesMountManagerImpl.resolveFile(VFSSpacesMountManagerImpl.java:129)
    at org.objectweb.proactive.extensions.dataspaces.core.DataSpacesImpl.resolveInputOutput(DataSpacesImpl.java:201)
    at org.objectweb.proactive.extensions.dataspaces.api.PADataSpaces.resolveOutput(PADataSpaces.java:472)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:231)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces$1.call(TaskProActiveDataspaces.java:228)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpace(TaskProActiveDataspaces.java:273)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.initDataSpaces(TaskProActiveDataspaces.java:228)
    at org.ow2.proactive.scheduler.task.data.TaskProActiveDataspaces.<init>(TaskProActiveDataspaces.java:118)
    at org.ow2.proactive.scheduler.task.ProActiveForkedTaskLauncherFactory.createTaskDataspaces(ProActiveForkedTaskLauncherFactory.java:43)
    at org.ow2.proactive.scheduler.task.TaskLauncher.doTask(TaskLauncher.java:184)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.objectweb.proactive.core.mop.MethodCall.execute(MethodCall.java:243)
    at org.objectweb.proactive.core.body.request.RequestImpl.serveInternal(RequestImpl.java:207)
    at org.objectweb.proactive.core.body.request.RequestImpl.serve(RequestImpl.java:153)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serveInternal(BodyImpl.java:561)
    at org.objectweb.proactive.core.body.BodyImpl$ActiveLocalBodyStrategy.serve(BodyImpl.java:486)
    at org.objectweb.proactive.core.body.AbstractBody.serve(AbstractBody.java:417)
    at org.objectweb.proactive.Service.serve(Service.java:119)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:203)
    at org.objectweb.proactive.Service.blockingServeOldest(Service.java:178)
    at org.objectweb.proactive.Service.fifoServing(Service.java:141)
```

Execute 
```java -jar botsing-reproduction-1.0.1.jar -crash_log SpaceNotFound.log -target_frame 3 -projectCP SCHEDULING_HOME/dist/lib/```

**Comment by pderakhshanfar** [comment]
@MaelAudren Yes, I agree with you. We should make sure that botsing works only with the software under test jar files. The missing libraries are:
- [ ] JUnit
- [ ] hamcerest
- [ ] Mockito
- [ ] ?

Can you please list all of the missing dependencies?

**Comment by MaelAudren** [comment]
@pderakhshanfar I discover the missing dependencies iteratively each time I relaunched Botsing. List all the missing dependencies could be very long. There could have more missing dependencies than there are dependencues in Botsing. Indeed dependency are transitive, which mean that Botsing dependencies have their own dependencies. In my last iteration I got the following exception ```java.lang.ClassNotFoundException: net.bytebuddy.dynamic.loading.ClassInjector$UsingReflection``` Regarding the exception I think it is a mockito dependency. Indeed I added the maven jars that doesn't contain the dependency neither.

**Comment by pderakhshanfar** [comment]
I tried to replicate your issue, I had this error:
Class 'org/objectweb/proactive/extensions/dataspaces/vfs/VFSSpacesMountManagerImpl.class' should be in target project, but could not be found!

Is this the same issue that you faced? If the answer is yes, then this problem shows that the given software under test dependencies are not complete.

**Comment by pderakhshanfar** [comment]
@MaelAudren I solved the problem that botsing had with JUnit, hamcrest, and Mockito. Can you please check if it solves your problem or not?

**Comment by pderakhshanfar** [comment]
The problem is solved in the latest release.

**Comment by MaelAudren** [comment]
@pderakhshanfar Can you update your comment and replace latest release by the release number. It will be clearer for a future usage.
