### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException 

### ISSUE THREAD

**Issue by assadOW2** [STAMP-project/botsing#52]
#### Characteristics
- **Reproducibility**: [always]
- **Severity**: [crash]
- **Execution Environment**: [Ubuntu 16.04]
- **Reporter**: [Assad Montasser, am@ow2.org

#### Description

Here is the complete terminal output, I attached the log file to the issue.

```
:~/OW2-Projects/Forks$ java -jar ~/STAMP-project/botsing/botsing-reproduction/target/botsing-reproduction-1.0.4-SNAPSHOT.jar -crash_log lutece-core/crash.log -target_frame 4 -project_cp lutece-core/
17:23:21.263 [main] INFO  eu.stamp.botsing.StackTrace - Exception type is detected:  fr.paris.lutece.portal.service.util.AppException
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1927)
	at eu.stamp.botsing.StackTrace.stringToStackTraceElement(StackTrace.java:98)
	at eu.stamp.botsing.StackTrace.setup(StackTrace.java:77)
	at eu.stamp.botsing.CrashProperties.setupStackTrace(CrashProperties.java:181)
	at eu.stamp.botsing.Botsing.setupStackTrace(Botsing.java:117)
	at eu.stamp.botsing.Botsing.parseCommandLine(Botsing.java:63)
	at eu.stamp.botsing.Botsing.main(Botsing.java:161)
```

I tried different target frame level but have the same issue.

Thanks for your help.

Assad

[crash.log](https://github.com/STAMP-project/botsing/files/2927271/crash.log)

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by pderakhshanfar** [comment]
Dear Assad,

The log file, which is passed to Botsing, should be in a certain format. It does not support chained stack traces (stack traces containing `caused by`). For instance, you can try this log:
```
java.lang.NullPointerException
at fr.paris.lutece.plugins.workflow.business.task.TaskDAO.selectTaskByIdAction(TaskDAO.java:184)
at fr.paris.lutece.plugins.workflowcore.service.task.TaskService.getListTaskByIdAction(TaskService.java:98)
at fr.paris.lutece.plugins.workflowcore.service.workflow.WorkflowService.doRemoveWorkFlowResourceByListId(WorkflowService.java:606)
at fr.paris.lutece.portal.service.workflow.WorkflowService.doRemoveWorkFlowResourceByListId(WorkflowService.java:447)
```

**Comment by assadOW2** [comment]
Thanks Pouria !

This solved my issue. Now I am facing a more challenging one, I will work on it and may open a new issue.

Have a nice day.
