### ISSUE TITLE
Failure in building Maven plugin

### ISSUE THREAD

**Issue by pderakhshanfar** [STAMP-project/botsing#75]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: random
- **Severity**: major
- **Tool/Service/Component**: Maven Plugin

#### Description
Maven plugin [test case](https://github.com/STAMP-project/botsing/blob/master/botsing-maven/src/test/java/eu/stamp/botsing/BotsingMojoTest.java) relies on the crash reproduction packaging. According to [this line](https://github.com/STAMP-project/botsing/blob/03cd33fbce99d4b120fa7ad8150ddd4c5f8e5ef0/botsing-maven/src/main/java/eu/stamp/botsing/BotsingMojo.java#L169) of the maven plugin Mojo file, maven plugin needs to have a jar file of crash reproduction for running. However, I cannot see the crash reproduction as the dependency of the maven plugin in [pom file](https://github.com/STAMP-project/botsing/blob/master/botsing-maven/pom.xml). So, if you build the maven plugin before building `botsing-reproduction`, the test will fail with the following error:
```
[ERROR] Plugin eu.stamp-project:botsing-maven:1.0.5-SNAPSHOT or one of its dependencies could not be resolved: Failure to find eu.stamp-project:botsing-maven:jar:1.0.5-SNAPSHOT in http://nexus.xwiki.org/nexus/content/groups/public-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-snapshots has elapsed or updates are forced -> [Help 1]
org.apache.maven.plugin.PluginResolutionException: Plugin eu.stamp-project:botsing-maven:1.0.5-SNAPSHOT or one of its dependencies could not be resolved: Failure to find eu.stamp-project:botsing-maven:jar:1.0.5-SNAPSHOT in http://nexus.xwiki.org/nexus/content/groups/public-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-snapshots has elapsed or updates are forced
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:128)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getPluginDescriptor(DefaultMavenPluginManager.java:181)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:286)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:241)
        at org.apache.maven.lifecycle.internal.MojoDescriptorCreator.getMojoDescriptor(MojoDescriptorCreator.java:239)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:103)
        at org.apache.maven.lifecycle.internal.DefaultLifecycleTaskSegmentCalculator.calculateTaskSegments(DefaultLifecycleTaskSegmentCalculator.java:83)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:89)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find eu.stamp-project:botsing-maven:jar:1.0.5-SNAPSHOT in http://nexus.xwiki.org/nexus/content/groups/public-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-snapshots has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:255)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:232)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:303)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:124)
        ... 21 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find eu.stamp-project:botsing-maven:jar:1.0.5-SNAPSHOT in http://nexus.xwiki.org/nexus/content/groups/public-snapshots was cached in the local repository, resolution will not be reattempted until the update interval of xwiki-snapshots has elapsed or updates are forced
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:240)
        at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:215)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:594)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:512)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:430)
        ... 25 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

        at org.apache.maven.it.Verifier.executeGoals(Verifier.java:1369)
        at org.apache.maven.it.Verifier.executeGoals(Verifier.java:1260)
        at eu.stamp.botsing.BotsingMojoTest.shouldExecuteBotsingMojoOnBotsingexampleProjectAndGenerateTestWithMavenVerifier(BotsingMojoTest.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

**Comment by luandrea** [comment]
Hi @pderakhshanfar,
the dependency from botsing-reproduction should be not necessary added in the pom.xml because Maven should handle it and download if necessary.
Obviously Maven cannot find dependency that are not in Maven Central and as I can see in your log it is missing a SNAPSHOT one (1.0.5-SNAPSHOT) which is not in Maven Central. In the test code it is not explicitly referenced that version, could you check your code if it's aligned with the STAMP GitHub repository?

**Comment by xdevroey** [comment]
Seems fixed.
