### ISSUE TITLE
Exception in thread "main" java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/botsing#95]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: Botsing Reproductions 1.0.8 snapshot
- **Execution Environment**: CentOS 7
- **Reporter**: Jesús Gorroñogoitia<jesus.gorronogoitia@atos.net>

#### Description
Hi @pderakhshanfar after your Botsing-Reproduction refactoring to show debug logs, I run it on one of our exceptions, after refactoring IFAuthenticationManager to use a default, no parameter constructor. But Botsing crashes throwing the following exception (this is the full Botsing output):
```
root@supersede:/home/supersede-if-botsing# ./run_botsing_exception16.sh 
12:39:56.449 [main] INFO  eu.stamp.botsing.StackTrace - Exception type is detected: org.wso2.carbon.user.core.UserStoreException
12:39:56.454 [main] INFO  eu.stamp.botsing.StackTrace - Target frame is set to: eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager:239)
12:39:56.454 [main] INFO  eu.stamp.botsing.StackTrace - Target Class is set to: eu.supersede.integration.api.security.IFAuthenticationManager
12:39:56.913 [main] INFO  e.s.i.properties.IntegrationProperty - Initializing IF configuration
Using default IF configuration: if.development.properties
12:40:29.020 [main] INFO  e.s.b.reproduction.CrashReproduction - Starting the dependency analysis. The number of detected jar files is 85.
12:40:34.127 [main] INFO  e.s.b.reproduction.CrashReproduction - Analysing dependencies done!
12:40:34.139 [main] INFO  e.s.b.t.s.BotsingIndividualStrategy - test generation strategy: Botsing individual
12:40:34.481 [main] DEBUG e.s.b.g.s.o.GuidedSearchUtility - Detecting the target method call(s) ...
12:40:34.482 [main] DEBUG e.s.b.g.s.o.GuidedSearchUtility - The target method is public!
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at eu.stamp.botsing.ga.strategy.operators.GuidedSearchUtility.collectPublicCalls(GuidedSearchUtility.java:35)
	at eu.stamp.botsing.fitnessfunction.testcase.factories.StackTraceChromosomeFactory.fillPublicCalls(StackTraceChromosomeFactory.java:206)
	at eu.stamp.botsing.fitnessfunction.testcase.factories.StackTraceChromosomeFactory.<init>(StackTraceChromosomeFactory.java:70)
	at eu.stamp.botsing.testgeneration.strategy.TestGenerationUtility.getChromosomeFactory(TestGenerationUtility.java:46)
	at eu.stamp.botsing.testgeneration.strategy.TestGenerationUtility.getGA(TestGenerationUtility.java:26)
	at eu.stamp.botsing.testgeneration.strategy.BotsingIndividualStrategy.generateTests(BotsingIndividualStrategy.java:61)
	at eu.stamp.botsing.reproduction.CrashReproduction.generateCrashReproductionTests(CrashReproduction.java:123)
	at eu.stamp.botsing.reproduction.CrashReproduction.execute(CrashReproduction.java:72)
	at eu.stamp.botsing.Botsing.parseCommandLine(Botsing.java:91)
	at eu.stamp.botsing.Botsing.main(Botsing.java:213)
```

#### Steps to reproduce
Botsing is executed with this script:

`java -jar botsing-reproduction-1.0.8.jar -Dsearch_budget=180 -Dpopulation=100 -Dtest_dir=../results/crash-reproduction-tests -crash_log ./logs/exception16b.log -target_frame 3 -project_cp ./libs -model ../results/models -Dp_object_pool=1.0 -Dsandbox=False
`

target runtime exception is:
```
org.wso2.carbon.user.core.UserStoreException: Cannot delete user who is not exist
	at eu.supersede.integration.api.security.IFUserStoreManager.handleException(IFUserStoreManager.java:573)
	at eu.supersede.integration.api.security.IFUserStoreManager.deleteUser(IFUserStoreManager.java:211)
	at eu.supersede.integration.api.security.IFAuthenticationManager.deleteUser(IFAuthenticationManager.java:239)
```

#### [Help on issue template](https://github.com/STAMP-project/EvoCrash/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by pderakhshanfar** [comment]
@jesus-gorronogoitia , can you please check if the line numbers in the target runtime exception match with the line numbers in the source code of the given software?

**Comment by jesus-gorronogoitia** [comment]
Hi @pderakhshanfar I've double checked. I've pulled botsing repo and it is up to date. I've compiled it again, but it generates the same jar (same size) than the one I used in this experiment. So that, what should I check to be sure I am using the botsing-reproduction version you are expecting?

**Comment by pderakhshanfar** [comment]
The problem is not about the version of botsing. It is about the version of you software. As an example, you can check your source code and see if line 239 of class `IFAuthenticationManager` is an statement of method `deleteUser` which calls `IFUserStoreManager.deleteUse()`

**Comment by jesus-gorronogoitia** [comment]
Yes, that line is correct in source code, but I will double check that the libraries loaded by Botsing are the correct ones

**Comment by jesus-gorronogoitia** [comment]
You were right. My SUT library was not adapted. Not it is working, although Botsing is not progressing  beyond 4.5 fitting function score. Closing this issue.
